name: Build and Deploy to AKS with Helm

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS Context
      uses: azure/aks-set-context@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

    - name: Build and Push Docker Image
      run: |
        az acr login --name ${{ secrets.REGISTRY_NAME }}
        docker build -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/demoimgyt:latest .
        docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/demoimgyt:latest

    - name: Deploy with Helm
      run: |
        helm upgrade --install namemhemcht ./helm \
          --set image.repository=${{ secrets.REGISTRY_NAME }}.azurecr.io/demoimgyt \
          --set image.tag=latest
